### ISSUE TITLE
Run C++ functional tests multiple times on CI

### ISSUE THREAD

**Issue by DanielKamkha** [heremaps/gluecodium#100]
"examples/scripts/build-cpp" script takes "--cpp NN" command line parameter, allowing C++ functional tests to be run for different C++ flavors. As Gluecodium generated code is intended to work with C++11, C++14, and C++17, it would be beneficial to run C++ functional tests several times for all these C++ flavors in Travis CI.

**Comment by utopalex** [comment]
In theory, for complete test coverage, one would not only have to consider the C++ revisions, but also version of library support. One could compile with the latest Clang, but only have use GCC libstdc++ instead of Clang libc++ available.
https://en.cppreference.com/w/cpp/compiler_support

**Comment by DanielKamkha** [comment]
That's a neat idea, but I'm mostly concerned about parts of generated C++ code where we intentionally put version-checking #ifdef-s to address C++ flavor variance. "Optional.h" and "type repository" mechanism are two such places, for example.
