### ISSUE TITLE
Function returning UInt? results in compilation failure on java

### ISSUE THREAD

**Issue by saebel1** [heremaps/gluecodium#1003]
API specification like
```
class Foo{
    fun bar() : UInt?
}
```
Leads to compilation errors in generated code on android. It complains about ambiguous convert_to_jni calls. The problem seems to be located in BoxingConversionUtils.hpp. For optionals, it only contains:
```
JNIEXPORT JniReference<jobject> convert_to_jni( JNIEnv* env, ::gluecodium::common::optional<bool> nvalue );
JNIEXPORT JniReference<jobject> convert_to_jni( JNIEnv* env, ::gluecodium::common::optional<float> nvalue );
JNIEXPORT JniReference<jobject> convert_to_jni( JNIEnv* env, ::gluecodium::common::optional<double> nvalue );
JNIEXPORT JniReference<jobject> convert_to_jni( JNIEnv* env, ::gluecodium::common::optional<int8_t> nvalue );
JNIEXPORT JniReference<jobject> convert_to_jni( JNIEnv* env, ::gluecodium::common::optional<int16_t> nvalue );
JNIEXPORT JniReference<jobject> convert_to_jni( JNIEnv* env, ::gluecodium::common::optional<int32_t> nvalue );
JNIEXPORT JniReference<jobject> convert_to_jni( JNIEnv* env, ::gluecodium::common::optional<int64_t> nvalue );
```
which prevents compiler from deciding which overload to use.

**Please note that swift/ dart might be also affected. Trying to use the same API for dart (on iOS) led to runtime errors. 
(App crashed/ debugger got disconnected when trying to debug- no further investigation was done for this platform).**

**Comment by DanielKamkha** [comment]
The fix was incorrect. The functions still miss the bodies. Also, the functional test does not catch this on Linux, so a smoke test needs to be added.
