### ISSUE TITLE
Unable to create lambda that has similar signature (same parameters, returning value) to already existing one

### ISSUE THREAD

**Issue by piotrkania-here** [heremaps/gluecodium#1026]
I was trying to add lambda_one but it turned that somewhere else in the project there was quite similar lambda_two.

lambda lambda_one = () -> Void
lambda lambda_two = () -> Void

The goal was to generate C++ to Swift (and Java) bindings. Instead following error was generated.

error: invalid redeclaration of 'copyFromCType'
135: internal func copyFromCType(_ handle: _baseRef) -> lambda_one {
135: bindings_main_glue.swift:63:15: note: 'copyFromCType' previously declared here
135: internal func copyFromCType(_ handle: _baseRef) -> lambda_two {

**Comment by DanielKamkha** [comment]
As a temporary workaround, you can declare one lambda to be a type alias to another.

**Comment by DanielKamkha** [comment]
Also fails in Java.
