### ISSUE TITLE
Inheritance chain fails to compile because base class is of incomplete type.

### ISSUE THREAD

**Issue by saebel1** [heremaps/gluecodium#1068]
Given following API specification:

```
open class Expression{
    internal fun toJson() : String
}

open class DoubleExpression : Expression{
    constructor create(value: Double)
}

class AdditionExpression : DoubleExpression {
    constructor createAddition(
        leftHandSide: DoubleExpression,
        rightHandSide: DoubleExpression
    )
}
```
generated c++ code fails to compile. Problem is that AdditionExpression.h just forward declares DoubleExpression. This fails of course as base class is of incomplete type. 

_Note: DoubleExpression.h is generated correctly (it includes Expression.h)_

**Comment by DanielKamkha** [comment]
The bug is triggered by this constructor:
```
constructor createAddition(
        leftHandSide: DoubleExpression,
        rightHandSide: DoubleExpression
    )
```
When the parent class is not referenced by the child anywhere else, the include is correctly added. But this constructor (or any other type reference) "forces" forward declaration.
