### ISSUE TITLE
@Equatable and @PointerEquatable do not work for Interfaces

### ISSUE THREAD

**Issue by Dschoordsch** [heremaps/gluecodium#108]
Generating
```
@PointerEquatable
interface PointerEquatableInterface {
}
```
for Swift the resulting protocol does not conform to Hashable. Same for `@Equatable`.

**Comment by DanielKamkha** [comment]
@PointerEquatable makes little sense for interfaces, as they are not guaranteed to be backed by a C++ implementation and thus might not have a pointer to compare for equality. So @PointerEquatable not being available for interfaces needs to be documented and validated against.

@Equatable, on the other hand, can work, so it needs to be implemented.
