### ISSUE TITLE
Loss of referential equality invariant due to interface inheritance

### ISSUE THREAD

**Issue by Blastbit513** [heremaps/gluecodium#1134]
According to this article [docs/rationales.md](https://github.com/heremaps/gluecodium/blob/master/docs/rationales.md) It's expected that an object which passed 2 or more times to C++ side will have the same internals.
And it does if the inheritance is not involved.

Example 1:
```kt
package test

interface ListenerA {
    fun actionA()
}

interface Provider {
    fun subscribeListenerA(listener: ListenerA)

    fun unsubscribeListenerA(listener: ListenerA)
}
```
usage
```kt
   val listener = ListenerA { ... }
   provider.subscribeListenerA(listener)
   // ... do something 
   provider.unsubscribeListenerA(listener)
```
This sequence works as expected and Provider gets the same shared_ptr's object on C++ side.

Whereas if the inheritance is involved it doesn't work for inherited interfaces passed through function which accepts base type. 
Example 2:
```kt
package test

interface ListenerA {
    fun actionA()
}

interface ListenerB : ListenerA {
    fun actionB()
}

interface ListenerC : ListenerB {
    fun actionC()
}

interface Provider {
    fun subscribeListenerA(listener: ListenerA)
    fun subscribeListenerB(listener: ListenerB)
    fun subscribeListenerC(listener: ListenerC)
    
    // all types of listeners
    fun unsubscribeListener(listener: ListenerA)
}
```
usage
```kt
   val listenerA = ListenerA { ... }
   provider.subscribeListenerA(listenerA)

   val listenerB = ListenerB { ... }
   provider.subscribeListenerB(listenerB)

   val listenerC = ListenerC { ... }
   provider.subscribeListenerC(listenerC)

   // ... do something 

   provider.unsubscribeListener(listenerA) // ok

   provider.unsubscribeListener(listenerB) // doesn't work, different object
   provider.unsubscribeListener(listenerC) // doesn't work, different object
```
This sequence doesn't work as expected. On the C++ side, the provider receives the different objects. 
In the debugger, I see that the passed object has the correct data (...CppProxyBase.jHashCode) deep inside.
But since shapred_ptr content is different it can't be matched against (for example in map).

**Comment by Blastbit513** [comment]
I took 10.2.3 release and faced a problem with build of generated JNI sources

There is a lack of includes of inherited classes in "base" class converters.

Used example 2 from the start message 

```cpp
#include "testlib_test_ListenerA__Conversion.h"
#include "testlib_test_ListenerAImplCppProxy.h"
#include "CppProxyBase.h"
#include "FieldAccessMethods.h"
#include "JniClassCache.h"
#include "JniWrapperCache.h"
#include <new>

....

std::shared_ptr<::test_lib::test::ListenerA> try_descendant_from_jni(JNIEnv* _env, const JniReference<jobject>& _jobj, std::shared_ptr<::test_lib::test::ListenerA>*) {
    if (_env->IsInstanceOf(_jobj.get(), CachedJavaInterface<::test_lib::test::ListenerC>::java_class.get())) {
        return convert_from_jni(_env, _jobj, (std::shared_ptr<::test_lib::test::ListenerC>*)nullptr);
    }
    if (_env->IsInstanceOf(_jobj.get(), CachedJavaInterface<::test_lib::test::ListenerB>::java_class.get())) {
        return convert_from_jni(_env, _jobj, (std::shared_ptr<::test_lib::test::ListenerB>*)nullptr);
    }
    return {};
}

```

I use clang (7+) and it doesn't compile, can't find `convert_from_jni` for these types.
Converters for ListenerB and ListenerC must be included as well.
```cpp
#include "testlib_test_ListenerB__Conversion.h"
#include "testlib_test_ListenerC__Conversion.h"
```

Compiles well If add manually.

**Comment by DanielKamkha** [comment]
Thanks for the detailed report. The initial fixes already addressed a similar issue for Dart, so won't be too difficult to use the same approach in JNI. I guess it did not pop up for JNI due to "unity builds" of C++ code in the tests.
