### ISSUE TITLE
Support enumeration mask

### ISSUE THREAD

**Issue by dev2575** [heremaps/gluecodium#1197]
Swift relies on OptionSet to handle masks of enumeration values.
Unless we missed it, there doesn't seem to be a way to support this in GlueCodium.
Instead, we are forced to exchange a List of distinct enumeration values, which is less than optimum.

**Comment by DanielKamkha** [comment]
How exactly do you want to support it? Which type should represent it in C++? In other languages (if it's relevant)?

**Comment by dev2575** [comment]
I believe the C++ and Java code generated is fine as is since we can support regular enums and masks of enums with it.

However, Swift crashes if the C++ pass a mask of enums with the current code generated.
I think having an option in the IDL to indicate which syntax to output for Swift would be useful.

Mode 1, the current syntax:
public enum MyEnum : UInt32, CaseIterable, Codable {
    case enum_1 = value_1
    case enum_2 = value_2
    ...
}

Mode 2, generate a struct that extends OptionSet:
struct MyEnum: OptionSetType {
    let rawValue: TYPE

    init(rawValue: TYPE) { self.rawValue = rawValue }

    static let enum_1 = MyEnum(rawValue: value_1)
    static let enum_2 = MyEnum(rawValue: value_2)
}
TYPE would typically be a UInt32 or UInt64.

**Comment by DanielKamkha** [comment]
According to `OptionSet` documentation (https://developer.apple.com/documentation/swift/optionset), the raw values of individual enumerators must all be powers of 2 to conform to this protocol. This means that C++ code also needs to be different from a regular enum. And, in turn, C++ code affects all other languages as well.

So "enums as flags" needs to be a general feature, not limited to Swift only. Still feasible, just more work.

**Comment by dev2575** [comment]
I agree that to use masks and bit-wise operations, the numbers must all be a power of 2.
You could do something to automate this but since it is already possible to do it by providing the values in the enum's IDL, I did not list this as a requirement. A simple documentation of that requirement could be enough.
If you do something for Java/C++, I think it would be good to still allow users to define the values as some people may want to use a specific range of values (i.e. 0x1000, 0x2000 .... instead of 0x1, 0x2, ...).

**Comment by DanielKamkha** [comment]
Here is the final approach I settled on. For this LIME IDL snippet
```
@Swift(OptionSet)
enum MyFlags {
    ONE = 1,
    TWO = 2,
    THREE = 4
}
class UseMyFlags {
    static fun getFlags(): Set<MyFlags>
}
```
the Swift code will have `MyFlags` generated as a `struct` conforming to `OptionSet` protocol (enumerators represented as `static let`). The Swift return value of `getFlags()` will be `MyFlags`, while sill being `std::unordered_set<MyFlags>` in C++.

**Comment by dev2575** [comment]
Hi Daniel,

Thank your for the update.
I haven't tested it yet, but could you please clarify why you use 'std::unordered_set<MyFlags> in C++' instead of just a simple MyFlags containing the mask of enumerations?

Best,
Francois
________________________________
