### ISSUE TITLE
java.lang.UnsatisfiedLinkError when using Duration type in Java

### ISSUE THREAD

**Issue by marius-campan** [heremaps/gluecodium#1209]
With a lime file containing similar declarations as:

class A {
static fun create(param1: Param1Type, duration: @Cpp(Type = "std::chrono::milliseconds") Duration) : SomeType
}

The following JNI code gets generated:

Java_com_a_b_c_A_create__Lcom_a_b_c_Param1Type_2Ljava_time_Duration_... 

Leading to a runtime exception of:

java.lang.UnsatisfiedLinkError: No implementation found for com.a.b.c.SomeType com.a.b.c.A.create(com.a.b.c.Param1Type, com.a.time.Duration) ...

Looks like the generated JNI uses in some cases the Java implementation of Duration.

**Comment by DanielKamkha** [comment]
Only happens for overloaded functions that have `Duration` type somewhere in their signature.
