### ISSUE TITLE
Use Flutter's finalisers to destroy message queue in C++

### ISSUE THREAD

**Issue by Hsilgos** [heremaps/gluecodium#1214]
Currently devs should call `LibraryContext.release()` to stop queue in C++
Sometimes it's hard to predict the exact time when this function must be called, so it leads to the situation when this function is not called.
When C++ wants to call some callback in Flutter isolate and this isolate is already destroyed and `LibraryContext.release()` in this this case iOS/Android main thread might hang forever (queue is not closed and waits when Flutter picks up the message).
To prevent such situation we may try to use Dart's finalisers. There must be global static object (`CallbackQueueStopper`?) in `LibraryContext` which does nothing, but when Flutter destroys isolate frees all objects it should call corresponding finaliser for the global static object. This finaliser should just call `cbqm.closeQueue(<current-isolate-id>)`. If isolate id is not available in finaliser then the global static object might store current isolate id during initialisation.
TBC: what is the order of finalisers calling? Random? FILO?
Existing mechanism with `LibraryContext.release()` may stay unchanged.

**Comment by DanielKamkha** [comment]
There is no official info on the order of execution of finalizers for Dart. Considering Dart is a GC language, and taking Java as a well-known GC language example, we should treat the finalization order as undefined. It's not random, but it's unknowable and unreliable.

**Comment by DanielKamkha** [comment]
The global static "context guard" object needs to be accessed from actual running code. Otherwise it will not be initialized, because Dart has lazy initialization for static variables.

**Comment by DanielKamkha** [comment]
Calling `LibraryContext.release()` from a finalizer is not possible. Finalizers are run from a GC thread. Sometimes it is a non-isolate thread, sometimes it's in isolate, but not flagged as "mutator". Either way, the thread is forbidden from calling back into Dart.

`LibraryContext.release()` does two things: cancels subscription to the sentry isolate's stream, and destroys the callback queue. The queue resides in "C++ world" and thus destroying it from a finalizer is simple. The question is the life cycle of the sentry isolate. This needs to be investigated further.

**Comment by DanielKamkha** [comment]
Cancelling the port subscription seems to be crucial. Stopping the callback queue presumably stops the sentry isolate by letting its "main" function to finish. This seems to have no effect on the port. So unless the subscription is cancelled explicitly, the port is kept alive, effectively hanging the main isolate on shutdown.

**Comment by DanielKamkha** [comment]
One possible approach to try: close the port from the sentry isolate (explicitly, at the end of its loop function).

**Comment by DanielKamkha** [comment]
Current working hypothesis: the isolate does not die until it has open port. So we have to somehow close the port automatically. We cannot close the port from any code triggered by finalizers, because finalizers of the static objects are executed only when the isolate dies. This creates a chicken-and-egg problem.

There's also, seemingly, no other meaningful "pre-termination" event to react to. `Isolate.addOnExitListener()` was proven experimentally to trigger on the same "isolate dies" event as finalizers.
