### ISSUE TITLE
Swift compilation errors when using types with the same name from different namespaces and frameworks

### ISSUE THREAD

**Issue by marius-campan** [heremaps/gluecodium#1218]
Project A defines a type T in namespace a through lime.
Project B uses A and defines a type T in namespace b through lime.

At compilation, the following error occurs:
<whatever>_main_glue.swift:10816:29: error: 'T' is ambiguous for type lookup in this context.

**Comment by DanielKamkha** [comment]
If both "projects" A and B are compiled into a single framework, this compilation error is correct. You cannot have two types with a same name inside the same framework.

**Comment by marius-campan** [comment]
You are right. Forgot that A gets imported as source code and not as framework into B.
