### ISSUE TITLE
Introduce async functions in Dart

### ISSUE THREAD

**Issue by Hsilgos** [heremaps/gluecodium#1306]
Asyncs in Dart are more important than in other supported languages (i.e. Java/Swift) because flutter plugin often works in native UI thread and in Dart isolate at the same time. Some functions are very desired to be called asynchronously in native UI thread. Currently it's possible with extensions in Dart. I.e. current approach looks like:

```
// lime
class Clazz {
    @Java(Skip)
    @Swift(Skip)
    internal lambda FooCallback = () -> Void

    @Java(Skip)
    @Swift(Skip)
    internal fun foo(foo_callback: FooCallback): Void
}

// Dart
extension AsyncClazz on Clazz {
    Future<void> foo() async {
        final completer = Completer<void>();
        internalfoo(() {
            completer.complete();
        });
        return completer.future;
    }
}

// C++
void
Clazz::foo(const FooCallback& callback)
{
    threading->runOnMainThread(
            [this]() {
                this->foo();
                callback();
            });
}
```
But Dart has its own limitation on usage of extensions. For example it's not possible to add static method in extension (which is visible 'through' extended class).

This is proposal for new feature in Gluecodium to support async methods. First of all there are following formal requirements:
- Implemented for Dart
- Must work with static and normal methods (currently no properties)
- Must support exceptions and non-void results

Basically the proposal is to introduce annotation `@Dart(Async)` which
1. Adds one more function in C++ with the same name and postfix `xxx_async` or `xxxAsync`. This function must have additional argument `async_callback` or `asyncCallback` which is intended to be called when result is ready.
2. On Dart side the annotated function must return `Future` and be declared as `async`
3. The Dart function must wrap call to `xxx_async`, create instance of [`Completer`](https://api.flutter.dev/flutter/dart-async/Completer-class.html) and process callback's result to complete `Completer` with error or result.

Example:

```
// Lime
class Clazz {
  fun foo(param: Int) : Bar throws Error

  // This declaration behaves almost like following:
  // internal lambda FooCallback = (Bar) -> Void
  // fun foo_async(async_callback: FooCallback, param: Int): Void 
}

// Dart, auto generated code
Future<void> foo(Int param) {
    final completer = Completer<void>();
    foo_async((result) {
        if (_hasError(result)) {
          completer.completeError(Baz(_getError(bar)));
        } else {
          completer.complete(_getResult(bar));
        }
    }, param);
    return completer.future;
}

// C++, manually written code
void Clazz::foo_async(std::function<void(gluecodium::Result)> callback, int param) {
  threading->callInMainThread([callback](){
    // Call to non-async functon
    gluecodium::Result result = foo(param);

    // Call async again to reduce chance of dead lock.
    threading->callInMainThread([callback](){callback(result);});
  });
}

```

**Comment by DanielKamkha** [comment]
As `@Dart(FooBar)` attributes are not supposed to affect other languages, I'd suggest to change the attribute to `@Async`. We can document that it works in Dart and affects C++ code, but has no effect on Java or Swift, yet. This way
```
class Clazz {
    @Async
    fun foo(): Void
}
```
would generate 2x `foo()` functions in C++: one with `callback` param, one without.

Another note, we should validate against `@Async` usages inside interfaces or on constructors.

**Comment by derolf** [comment]
+1
