### ISSUE TITLE
When are structs copied?

### ISSUE THREAD

**Issue by derolf** [heremaps/gluecodium#1309]
Please make clear in the documentation in what cases structs are copied:
- as arguments (no?)
- as return values (yes?/moved in c++?)
- passed as arguments across language boundaries (yes?)

**Comment by DanielKamkha** [comment]
Structs are copied by Gluecodium-generated bindings only when crossing a language boundary (in any direction). So you got the bullet #3 right. 

Passing structs around within the same language (as parameters or as return values) behaves according to the rules of that language. Gluecodium does not affect it in any way. In Java and Dart they are classes and thus are passed by reference all the time. In Swift they are structs and are passed by value.

For C++, if a function returns a struct, Gluecodium generates a by-value return type. However, Gluecodium generates only abstract classes. Whether the return value is moved or not, depends solely on the implementer.
