### ISSUE TITLE
Use std::string_view instead of std::string for keys in Java class cache 

### ISSUE THREAD

**Issue by Hsilgos** [heremaps/gluecodium#1423]
Current implementation looks like
```
std::unordered_map<std::string, jni::JniReference<jclass>*>& get_instance_class_map()
{
    static std::unordered_map<std::string, jni::JniReference<jclass>*> classes;
    return classes;
}
```
This map is basically filled once at start and then immutable. Makes sense to use std::string_view as key after Gluecodium switches to C++17. 
Consider to use std::string_view for `TypeRepository`, `CachedJavaClass`, etc.

**Comment by DanielKamkha** [comment]
Prerequisite: #1422
