### ISSUE TITLE
Compilation fails on MSVC (version 9.3.5 onwards)

### ISSUE THREAD

**Issue by modus-x** [heremaps/gluecodium#1445]
#1015 (commit [d0cef58](https://github.com/heremaps/gluecodium/pull/1015/commits/d0cef5824436dfbf42a69ce7e52a512fc07b20c4)) leads to MSVC compilation error C2492 - data with thread storage duration cannot have dll interface.

**Comment by Hsilgos** [comment]
@DanielKamkha , pimpl to hide implementation in cpp?
