### ISSUE TITLE
Issue with declaration order

### ISSUE THREAD

**Issue by Hsilgos** [heremaps/gluecodium#1467]
Following lime leads to uncompilable code in C++

```
@Skip(Swift) @Skip(Dart)
internal interface Base {
    interface FooChecker {
        static fun foo(
        )
    }
    lambda SomeLambda = (FooChecker) -> Base
}
```

Because lambda is declared before class FooChecker in C++ header

**Comment by DanielKamkha** [comment]
I bet lambdas are just not considered by the "topological sort" algorithm we currently have.
