### ISSUE TITLE
Parser fails on // in last element of enum

### ISSUE THREAD

**Issue by Contilehpat** [heremaps/gluecodium#1506]
Parser fails on // in last element of enum. I.e.:
```
package Example
enum Example
{
    FOO = 0, // foo
    BAR = 1  // bar
}
```

Results in:
com.here.gluecodium.loader.LimeBasedLimeModelLoader loadFile: File e:\casdev\JSON_Streaming_PC\idl\example.lime, line 5:13, mismatched input '//' expecting {NewLine, ',', '}'}

**Comment by DanielKamkha** [comment]
LIME IDL supports two kinds of comments:
* documentation comments (`//`, `/* */`) are transformed into code comments in generated code
* "local" comments (`#`) are comments to LIME definition itself and are discarded during generation

Of these, only `#` comments can be freely put anywhere. The `//` comments must precede the element they describe (as they are intended to be documentation).

Therefore, the correct syntax for your LIME definition would be
```
package Example
enum Example
{
    // foo
    FOO = 0,
    // bar
    BAR = 1
}
```
if your intend for these comments to appear in generated code as well.
