### ISSUE TITLE
Q: Can by-ref parameter/return modeled in external types 

### ISSUE THREAD

**Issue by derolf** [heremaps/gluecodium#1512]
(Couldn’t find a discussion forum)

```
class A {};

class B {
  void foo(A& a) {
    a.bar(); // call non-const function 
  }
  
  B& setX(int x) {
    return *this; // return reference to itself
  }
};
```

Can we model external class with LIME that

a) pass mutable parameters by reference
b) return a mutable reference to itself (builder-chaining)

**Comment by Hsilgos** [comment]
**NO** to both questions. I can't imagine scenario when mutable type is passed from Java/Swift/Dart or vice versa. 
It's possible to return const reference though and you can try to implement builder using bunch of const_cast. We got rid off all builders in out project, but when we had them we used `std::shared_from_this` + methods which returned shared pointers to self.
