### ISSUE TITLE
LimeIDL example code from the documentation throws errors

### ISSUE THREAD

**Issue by sereksim** [heremaps/gluecodium#1517]
If I use the example from the lime documentation [gluecodium/docs/lime_idl.md](https://github.com/heremaps/gluecodium/blob/master/docs/lime_idl.md) there is an error:
`com.here.gluecodium.loader.LimeBasedLimeModelLoader loadFile: File C:\Users\...\Gluecodium\test.lime, line 39:0, mismatched input '}' expecting NewLine`

After correcting the file the end looks like this:
````
...
    const DefaultOptions: SomeImportantProcessor.Options = {flagOption = true, uintOption = 42, {}
	}
}
````
but it still throws an error: `com.here.gluecodium.loader.LimeBasedLimeModelLoader loadFile: File C:\Users\...\Gluecodium\test.lime, line 40:0, mismatched input '}' expecting NewLine`

Using another simple file to test the Loader throws an error as well, although the syntax should be correct according to the documentation:
```
package test

class HelloWorldClass {
	fun getHello(
        str: blob,
	len: int
    )
}
```
=> `com.here.gluecodium.loader.LimeBasedLimeModelLoader loadFile: File C:\Users\...\Gluecodium\HelloWorld.lime, line 8:1, mismatched input '<EOF>' expecting NewLine`

Tbh, at this point I'm not sure anymore if I haven't just simply misunderstood the LimeIDL syntax, but if there are errors in the documentation as well, then maybe there is another reason...

**Comment by Hsilgos** [comment]
@sereksim in your second simple example 2 issues:
1. lime must end with new line
2. Default types starts with capital letter (syntax is case sensitive)

Also you have mix of spaces and tabs, but Gluecodium should deal with it
Try this:
```
class HelloWorldClass {
  fun getHello(
    str: Blob,
    len: Int
    )
}

```

**Comment by sereksim** [comment]
Thanks for your quick response :) The example works now!

**Comment by Hsilgos** [comment]
@sereksim , hi. I added the first [example](https://github.com/heremaps/gluecodium/blob/master/examples/calculator/README.md)
