### ISSUE TITLE
Lambda parameters and return value docs don't work for cpp,swift and dart.

### ISSUE THREAD

**Issue by limingchina** [heremaps/gluecodium#1544]
Currently, with the following input:
```
package test

class CommentsLambda {
    // This is a comment for lambda 
    // @param[p0] This is the comment for the first parameter of the lambda.
    // @param[p1] This is the comment for the second parameter of the lambda.
    lambda MyCallback = (@Java("param1_name") Int?, @Java("param2_name") String) 
        ->  /*Comment for return value*/ Int
} 
```
The documentation for parameters will not appear in the generated documentation for the lambda. The comment for the return value will lead to a lime file loading error since the syntax is not supporting documenting the return value.

**Comment by pwrobeldev** [comment]
The support was added long time ago via https://github.com/heremaps/gluecodium/pull/1546

I am closing this ticket.
