### ISSUE TITLE
Reference Links to Other Classes Are Broken

### ISSUE THREAD

**Issue by jehovahmidara** [heremaps/gluecodium#221]
At the moment, we have a challenge of referencing classes from other modules within the lime files. An example is that of the Geocircle **(See the Code snippet below)** .

```
// Represents a circle area in 2D space.
// An instance of this class can be used during the creation of the [sdk.mapviewlite.MapCircle] class
// to represent a circle on the map.
@Equatable
@Immutable
struct GeoCircle {
}
```

There are 2 mapview classes with different names within our project module, with one having the name **mapviewlite** and the other **mapview-harp**.

Referencing the mapcircle class within the API Documentation for that of **mapviewlite** will result in a broken link for the **mapview-harp** API Documentation. 

It seems like gluecodium does not know which of the reference class to point to.

I currently see this as a bug and will not mind having a fix for this as other classes within our project module are affected by this bug. Thanks

**Comment by jehovahmidara** [comment]
Re-opening this ticket:


As mentioned earlier, referencing other classes with similar file names from a description within the lime files results in a broken link within the generated API Reference files for the DOC Variants for both Android and iOS . 

An example is that of GeoPolygon (See the Code snippet below) .

```
// Represents a GeoPolygon area as a series of GeoCoordinates.
// An instance of this class, initialized with the appropriate vertices, can
// be used during the creation of the [sdk.mapview-harp.MapPolygon] class to represent a
// polygon on the map.
```

**Expected (Lite Variant)**
Represents a GeoPolygon area as a series of GeoCoordinates. An instance of this class, initialized with the appropriate vertices, can be used during the creation of the [MapPolygon](https://docs.in.here.com/static/28182/290436/html/Classes/MapPolygonLite.html) class to represent a polygon on the map.

**Actual (Lite Variant)**
Represents a GeoPolygon area as a series of GeoCoordinates. An instance of this class, initialized with the appropriate vertices, can be used during the creation of the **[sdk.mapview.MapPolygon]** class to represent a polygon on the map.

**Expected (Explore Variant)**
Represents a GeoPolygon area as a series of GeoCoordinates. An instance of this class, initialized with the appropriate vertices, can be used during the creation of the [MapPolygon](https://docs.in.here.com/static/28182/290438/html/Classes/MapPolygon.html) class to represent a polygon on the map.

**Actual (Explore Variant)**
Represents a GeoPolygon area as a series of GeoCoordinates. An instance of this class, initialized with the appropriate vertices, can be used during the creation of the [sdk.mapview.MapPolygon] class to represent a polygon on the map.

It seems like gluecodium does not know which of the reference class to point to.

I currently see this as a bug and will not mind having a fix for this as other classes within our project module are affected by this bug. Thanks

**Comment by DanielKamkha** [comment]
You documentation reference is invalid. It says [sdk.mapview-harp.MapPolygon]. sdk.mapview-harp package does not exist. It should be either sdk.mapview or sdk.mapviewlite, not sure which one did you mean.
