### ISSUE TITLE
Class doesn't see enum, which located inside of another class (iOS only)

### ISSUE THREAD

**Issue by igor-maliukh** [heremaps/gluecodium#260]
I have class VenueService. And I put enum InitStatus inside it. I also have interface VenueServiceListener, which need to use this enum as well. And VenueService from another hand also use VenueServiceListener. When I try to generate classes on iOS, I get error in my cbridge classes:

output-swift/cbridge/include/sdk/venue/service/cbridge_VenueServiceListener.h:35:98: Unknown type name 'sdk_venue_service_VenueService_InitStatus'

Here is simplified versions of VenueService and VenueServiceListener lime files:

    package sdk.venue.service

    class VenueService {

        enum InitStatus {
            ONLINE_SUCCESS,
            OFFLINE_SUCCESS,
        }

        fun add(
            listener: VenueServiceListener
        )
    }

    package sdk.venue.service

    import sdk.venue.service.VenueService.InitStatus

    interface VenueServiceListener {
        @Cpp("onInitializationCompleted")
        fun on_initialization_completed(
            result: InitStatus
        )
    }

**Comment by DanielKamkha** [comment]
Seems to be caused by a circular dependency between these two types.
