### ISSUE TITLE
Gluecodium Strips Whitespaces from Nested Lists

### ISSUE THREAD

**Issue by jehovahmidara** [heremaps/gluecodium#304]
Gluecodium ignores the nested lists syntax specified within the lime files which leads to just a single list generated within the API docs.

An example of a current nested-list specified syntax within the lime files:

**Lime file description**
```
// Continent Names:
// - Africa
// - European Countries:
//   - Spain
//   - Germany
//   - Italy
// - African Regions
//   - West Africa
//   - East Africa
//   - North Africa 
```

**Generated docs:**
Continent Names:
- Africa
- European countries
- Spain
- Germany
- Italy
- African Regions
- West Africa
- East Africa
- North Africa 

**Expected Generated docs**
Continent Names:
- Africa
- European Countries
     - Spain
     - Germany
     - Italy
- African Regions
     - West Africa
     - East Africa
     - North Africa

**Comment by DanielKamkha** [comment]
There are actually two separate issues here. First is LimeIDL parser trimming leading whitespace, demoting nested lists to non-nested. This is fixable in Gluecodium own parser(s).

The second issue is specific to Swift. Swift documentation says that nested lists should be indented with 4 spaces, but Flexmark parser-renderer for Markdown we use internally outputs them with 2, regardless of the number of spaces in the original text. This needs to be configured or circumvented somehow.
