### ISSUE TITLE
Provide unified support for locales across languages

### ISSUE THREAD

**Issue by devcooch** [heremaps/gluecodium#372]
All modern mobile platforms are providing proper support for locales.
iOS:
- https://developer.apple.com/documentation/foundation/nslocale
- https://developer.apple.com/documentation/foundation/locale
Android:
- https://developer.android.com/reference/java/util/Locale
Flutter:
- https://api.flutter.dev/flutter/dart-ui/Locale-class.html

Please implement support for `Locale` type in Gluecodium, so that we can reuse it.
The suggestion is to base the interface on Flutter interface as most lean and fully covering a majority of common use case.
Hence the following is needed:
- language
- country
- script

Additionally converting function for BCP-47 string is appreciated.

**Comment by DanielKamkha** [comment]
As Gluecodium generates Dart code without a Flutter dependency, the most likely candidate for a Dart representation of the Local type is the one from `intl` package: https://pub.dev/documentation/intl/latest/locale/Locale-class.html.

**Comment by DanielKamkha** [comment]
I think that providing any public functions to convert between locale string formats is out of scope for Gluecodium. Gluecodium generated code provides bindings between mobile-platform languages and C++. Any internal conversion required to correctly transport a Locale object across languages is in scope. But providing additional public utility is not.

**Comment by devcooch** [comment]
Agree on both points.
