### ISSUE TITLE
Provide unified support for Color

### ISSUE THREAD

**Issue by Hsilgos** [heremaps/gluecodium#390]
[Java](https://developer.android.com/reference/android/graphics/Color), [Swift](https://developer.apple.com/documentation/uikit/uicolor) and [Dart](https://api.flutter.dev/flutter/dart-ui/Color-class.html) have quite similar representation of Color.

All representations have constructors or factory methods accepting red, green, blue, alpha components as  parameters and all representation have possibilities to retrieve RGBA.

`Swift` keeps accepts and retrieves `floats`, `Java` also may work with `floats`, `Dart`  works with `integers`.
I propose to pass RGBA to/from C++ with 4 floats to prevent loosing precision. 
`C++` should have custom implementation, something like

```
struct Color {
  float red, green, blue, alpha;

  constexpr Color(float red, float green, float blue, float alpha) noexcept
     :red(red),green(green),blue(blue),alpha(alpha) {}

  constexpr Color(float red, float green, float blue) noexcept
    :Color(red, green, blue, 1.f) {}

  constexpr Color clamped() const {
    return Color(std::clamp(red, 0f,1f),
                          std::clamp(green, 0f,1f),
                          std::clamp(blue, 0f,1f),
                          std::clamp(alpha, 0f,1f));
    } 
};
```

Remember that `std::clamp` is `C++17`, can be replaced with `std::min(1f, std::max(0f, color))`

`Dart` can convert float to integer, something like
```
green_uint8 = green_float >= 1.0 ? 255 : green_float * 256.0;
green_float = max(0, min(255, (green_uint8 * 256.0).floor()));
```

**Comment by DanielKamkha** [comment]
Both Swift and Dart types linked are parts of their respective UI frameworks. By design, Gluecodium generated code was free of UI dependencies so far. Moreover, specifically for Swift adding UIKit as a dependency will make the generated code uncompilable on Linux and thus untestable on Linux.

**Comment by DanielKamkha** [comment]
A more flexible (if more complicated) approach would be to extend current C++-only functionality of "external types" to also apply to Java/Swift/Dart. This way Color can be implemented as an "external type" on user side.

**Comment by DanielKamkha** [comment]
The consensus is that "external types" support for Java/Swift/Dart is a better approach for this (see https://github.com/heremaps/gluecodium/issues/408).
