### ISSUE TITLE
Support wider range of cmake versions

### ISSUE THREAD

**Issue by VeaaC** [heremaps/gluecodium#404]
When using gluecodium we often get warnings like
`  CMake < 3.15 is obsolete and may work incorrectly with Gluecodium `

Is it possible to support a wider range of cmake versions? E.g. Ubuntu 19.10 (less than 1 year old) ships with cmake version 3.13.4

**Comment by DanielKamkha** [comment]
The most limiting factor is CMake support for Xcode builds. @Hsilgos may provide more detail.

**Comment by VeaaC** [comment]
I guess it depends on the platform on builds for, e.g. I imagine on Linux you will not have many restrictions on using older cmake versions.
