### ISSUE TITLE
Link Smoke tests in documentation

### ISSUE THREAD

**Issue by DanielKamkha** [heremaps/gluecodium#44]
[Original issue by @Dschoordsch]

As an API designer it's sometimes difficult to understand the documentation without additional examples. Since Genium already has smoke tests for all features, it would be nice if those were easily accessible per feature and linked from the documentation.

**Comment by Dschoordsch** [comment]
Any reason why this was closed?

**Comment by DanielKamkha** [comment]
I don't see a way do to this with the current structure of the documentation. Which also means, of course, that the documentation is poorly structured right now. If you have concrete ideas on this, please propose here.
