### ISSUE TITLE
@Cpp ExternalType support for struct

### ISSUE THREAD

**Issue by DavidePomi** [heremaps/gluecodium#460]
While the following syntax works for classes, it seems like it does not work for structures:

```
@Cpp(ExternalType = "physical_path/MyStruct.hpp", ExternalName = "::logical_path::MyStruct")
internal struct MyStruct {
}
```

**Comment by DanielKamkha** [comment]
"External type" definitions are supported for structs. If they do not work, it might be a bug. Please provide a minimal example to reproduce the issue. In this case, a minimal C++ header file as well as the IDL definition for your struct (with fields). Also please prove the details of the compiler error your get.

**Comment by DanielKamkha** [comment]
Not reproducible due to lack of information.
