### ISSUE TITLE
Deprecate individual values from an enum

### ISSUE THREAD

**Issue by LucianMachison** [heremaps/gluecodium#517]
Applying the @Deprecated tag to an enum value and not the whole enumeration will have as effect an error when building in Swift because the enumeration "does not conform to protocol 'CaseIterable'.

**Comment by DanielKamkha** [comment]
From CaseIterable docs (https://developer.apple.com/documentation/swift/caseiterable, emphasis mine):

> The compiler can automatically provide an implementation of the CaseIterable requirements for any enumeration **without** associated values or **@available attributes on its cases**.
