### ISSUE TITLE
Add support for free-form platform attributes

### ISSUE THREAD

**Issue by cuteqt** [heremaps/gluecodium#543]
Swift supports to add attribute to the functions. i.e. for functions with trivial return value,
without `@discardableResult` the Swift developers have to use:
_ = A.func(...)

with `@discardableResult` the user could simply use:
A.func(...)
and not worry about compiler warning.

This is just an example. There are many other useful attributes available in Swift, Java and C++. It would be nice to support it in gluecodium.

**Comment by Hsilgos** [comment]
Java, Swift and C++ all support attributes on functions. It would be nice to support such attributes generally.

**Comment by DanielKamkha** [comment]
Dart also supports attributes. All these languages also support attributes on most elements, not just functions.

Moreover, the existing `@Swift(ObjC)` IDL attribute could be converted to this general system.

**Comment by DanielKamkha** [comment]
I propose platform-attribute syntax for this. For example, to add a `@discardableResult` attribute in Swift generated code, one would mark a function in IDL with `@Swift(Attribute="discardableResult")` IDL attribute.

**Comment by DanielKamkha** [comment]
One additional possible usage for this would be platform-specific deprecation attributes, e.g. `@Java(Attribute="@Deprecated(\"foo bar\")"`. This needs to be properly documented.
