### ISSUE TITLE
Add enum to string conversion in C++

### ISSUE THREAD

**Issue by lorensi** [heremaps/gluecodium#550]
It's quite common for developers to create their own conversion function. If these conversions could be created by Gluecodium itself that would eliminate a bunch of user code.  

lime:
```
package sdk;

enum Foo {
  BAR,
  BAZ
}
```

Possible generated code:
```cpp
namespace sdk {

enum class Foo {
  BAR,
  BAZ
}

std::string_view                    // or std::optional<std::string_view>
to_string(Foo foo) {
  switch (foo) {
    case Foo::BAR: return "BAR"sv;  // or "Foo::Bar"
    case Foo::BAZ: return "BAZ"sv;  // or "Foo::Baz"
  }
  return "<unknown>"sv;             // or std::nullopt; 
}

}
```

Usage:
```cpp
#include <sdk/Foo.h>

namespace something {
  void compute(Foo foo) {
     std::cout << to_string(foo); // Note the unqualified call. ADL taking place here.
  }
}
```

If it's a problem to create those functions for all enums, I suggest then to create at least a new attribute to indicate that the user wants these functions to be generated by Gluecodium, like the following:

```
@Cpp(Stringify)
enum Foo {
  BAR,
  BAZ
}
```

**Comment by DanielKamkha** [comment]
Creating a new attribute makes sense. Generating this for every enum would have been too much dead code.

**Comment by Hsilgos** [comment]
If such generated code will be used only internally (not through external functions) then those converters might be header-only and compiler won't add them to final binary (except those which are really were used)
