### ISSUE TITLE
Example: Add example of overriding a C++ virtual function in platform code

### ISSUE THREAD

**Issue by iamsergio** [heremaps/gluecodium#582]
Suppose you have a C++ class:
```
class MyClass {
    int bar() { return foo(); }
    virtual int foo() const { return 42 };
};
```

and the corresponding auto-generated Dart class too.
The user should be able to derive from MyClass in Dart, override `foo()`, and his `foo` get called whenever `bar()` gets called in C++.

Is this possible already ? If yes then an example in the examples/ directory would be great.

**Comment by DanielKamkha** [comment]
It's not a scenario we've used in production or tests yet. But it looks to be possible with the current functionality. I'll commit an example and then let's see if I understood the scenario correctly.

**Comment by DanielKamkha** [comment]
Added functional test as an example, please have a look: #586

**Comment by Hsilgos** [comment]
I'm not sure that I understand your case correctly.
If you declare MyClass as interface Gluecodium will generate abstract class in Dart from which you may derive. Then you can pass this object to C++ and you will able to call foo and bar in C++ and corresponding method will be called in Dart.
You should try to use this mechanism.
If you want to connect non-empty manually written class in C++ with Dart (Java, Swift) directly you will have to use external types and describe all transitive types and method calls. In this case I would use delegation.
