### ISSUE TITLE
Documentation links are sometimes generated incorrectly

### ISSUE THREAD

**Issue by hitman-codehq** [heremaps/gluecodium#608]
If you have a documentation link in a some_class.lime file such as the following:

// To do something, call [OtherClass.some_method]

Where OtherClass is defined in the other_class.lime file, then the expected generated Dart comment in SomeClass.dart would be the following:

// To do something, call [OtherClass.myMethod]

This allows Dartdoc to correctly link to the target method.  But the generated Dart code is actually:

// To do something, call [myMethod]

This causes a Dartdoc warning something like:

warning: unresolved doc reference [myMethod], from something.SomeClass: (file:///... some_class.dart)

The generated HTML documentation is still readable, but there is no link to the myMethod.

There is also a second, similar but different, problem.

Let's saqy that a Lime file contains:

enum MyError {
  AN_ERROR_VALUE = 1
}

When referencing this error value from another Lime file's documentation, one would type something like:

// Returns [MyError.AN_ERROR_VALUE] on error

In Generated code, the enum is generated as

enum MyError {
  anErrorValue
}

So the generated Dart documentation should also be:

// Returns [MyError.anErrorValue] on error

But it is in UPPER_CASE, so also generates a Dartdoc warning.

**Comment by DanielKamkha** [comment]
Could not reproduce the enumerator issue. Probably a reference resolution failure. Might be still caused by a bug, but need more information to investigate.
