### ISSUE TITLE
Add support for nested exception in structs

### ISSUE THREAD

**Issue by pbula** [heremaps/gluecodium#846]
The following will fail to generate, because `exception` declaration nested inside a `struct` is not supported. 

```
struct ThrowingStruct {
    field: String

    enum InstantiationErrorCode {
        WHATEVER = 1
    }

    @Java("InstantiationException")
    exception Instantiation(InstantiationErrorCode)

    constructor make() throws Instantiation
}
```

The same works for `class` and it would be great to have it supported for structs as well.

**Comment by DanielKamkha** [comment]
I'd assume the attributes on the `struct` declaration are irrelevant. This would fail for any struct.

**Comment by pbula** [comment]
> I'd assume the attributes on the `struct` declaration are irrelevant. This would fail for any struct.

Ah yeah, I removed a bit too much from my example to make it "minimal" :-)
