### ISSUE TITLE
Question: conversion between gluecodium::optional and std::shared_ptr

### ISSUE THREAD

**Issue by turekj** [heremaps/gluecodium#875]
First of all, I'd like to thank you for this amazing library! 👏  As a Djinni convert, I'm really impressed by the feature set provided out-of-the-box. Gluecodium makes working with cross-platform C++ a beautiful experience. ❤️ 

I got a conceptual question about a rather unconventional usage of the Gluecodium. I hope it's not a problem to ask it here but if it's not the right place to do so please close this issue with no response. 😄 

I'm using auto-generated `flatbuffers` structures that I'd like to pass to the native layer from the C++ code. Short example:

```cpp
struct PostT {
  std::string id;
  std::shared_ptr<UserT> author;
  std::vector<std::shared_ptr<CommentT>> comments;
```

where `UserT` and `CommentT` are also plain structures. I'm able to publish `id` field of this structure to native code using gluecodium's external types:

```
struct TimelinePost {
    external {
        cpp include "Post_generated.h" 
        cpp name "::fbs::feed::PostT"
    }

    id: String
}
```

I'm struggling with optional types, though. Unfortunately, the `flatbuffers` use an obscure method of modeling optionals via pointer types. I know that I can write an adapter class for each type that would expose the fields using `gluecodium::optional` via getters but I really want to avoid writing/generating this code. 

Is there any concept in the Lime IDL you can point me towards that would help solve this problem? So far I came up with the following:

* Implement a custom type that would combine both `std::shared_ptr` and `std::optional` and use it as a `GLUECODIUM_OPTIONAL_TYPE`. I'll try this approach next but I'm not sure if I can get the API right to support both of them.
* Pass `flatbuffers` as bytes (serialized) between the layers and write custom native conversions. This approach has the same flaw as writing adapter classes - each type needs its own converter.

Thank you!

**Comment by DanielKamkha** [comment]
Thank you for your interest and the kind words! Now to the technical part.

First of all, please note that `gluecodium::optional` type is a stand-in for `std::optional` for C++ compilers prior to C++17. When you're compiling with C++17 or later, `gluecodium::optional` is just a typedef to `std::optional`.

There's also a mechanism for using a user-supplied `optional` type. See documentation comments in https://github.com/heremaps/gluecodium/blob/master/gluecodium/src/main/resources/templates/cpp/common/Optional.mustache for details (it's a C++ header file). However, the custom `optional` type still needs to mimic `std::optional` API, at least partially. So it may or may not be possible to have a universal adapter for flatbuf optionals this way, depends on how convoluted they are.

**Comment by Hsilgos** [comment]
Hi, @turekj , thinks for your feedback!

Currently I think that most promising approach is to create custom type which combines optional with shared_ptr. For C++ -> Platform direction It doesn't look complex, just wrap `std::optional` inside and create implicit converters. For opposite direction there also might be custom operator.
