### ISSUE TITLE
Logical AND for @Skip annotation

### ISSUE THREAD

**Issue by saebel1** [heremaps/gluecodium#980]
Multiple @Skip annotations for the same element are currently combined with logical OR (i.e. element gets skipped if one of the provided tags is present). 

In addition, logical AND should be added in order to enable element skipping only if multiple tags are present. Please note that this AND needs to be combinable with platform tags, like 
```
@Skip(Java AND "CustomTag") 
```
to skip java code generation for given element if CustomTag is present.

**Comment by DanielKamkha** [comment]
Clarified the use case with @saebel1:
> I want to combine one platform tag with one custom tag. Even though, there will be multiple of these combinations per element (to combine java AND custom, swift AND custom, dart AND custom).

Combining two custom tags with AND logic could be, if needed, done outside of Gluecodium on build-system level. Combining two platform tags with AND logic does not make much sense.

Considering all of the above, introducing any support for complex logical expressions in the `@Skip` tag sounds like a definite overkill. The intended use case could be achieved with a simpler approach of "custom tags inside platform tags". E.g., for Java:
```
@Java(Skip) # current syntax
@Java(Skip = "CustomTag") # new extended syntax
```

The extended syntax is backwards compatible with the current one, `@Java(Skip)` is treated as having an empty list of custom tags, thus resulting in skip-always-in-Java behavior as before.
